files:
  - source: src/main/resources/assets/spectrum/lang/en_us.json
    translation: /src/main/resources/assets/spectrum/lang/%locale_with_underscore%.json
  - source: /src/main/resources/data/spectrum/patchouli_books/guidebook/en_us/categories
    translation: /src/main/resources/data/spectrum/patchouli_books/guidebook/%locale_with_underscore%/categories/%original_file_name%
  - source: /src/main/resources/data/spectrum/patchouli_books/guidebook/en_us/entries/brewing
    translation: /src/main/resources/data/spectrum/patchouli_books/guidebook/%locale_with_underscore%/entries/brewing/%original_file_name%
  - source: /src/main/resources/data/spectrum/patchouli_books/guidebook/en_us/entries/creating_life/
    translation: /src/main/resources/data/spectrum/patchouli_books/guidebook/%locale_with_underscore%/entries/creating_life/%original_file_name%
