files:
  - source: src/main/resources/assets/spectrum/lang/en_us.json
    translation: /%locale_with_underscore%/src/main/resources/assets/spectrum/lang/%locale_with_underscore%.json
  - source: src/main/resources/data/spectrum/patchouli_books/guidebook/en_us/**/*.json
    translation: /%locale_with_underscore%/%original_path%/%original_file_name%
